BankAccount/urls.py
from django.urls import path, include
from .views import create_bank_account, bank_account_details
from deposit.views import  deposit_funds , deposit_history
from transaction.views import send_funds_out, send_funds_within, transaction_history

urlpatterns = [
    path('create/', create_bank_account, name='create_bank_account'),
    path('details/', bank_account_details, name='bank_account_details'),
    path('deposit/', deposit_funds, name='deposit_funds'),
    path('sendout/', send_funds_out, name='send_funds_out'),
    path('sendwithin/', send_funds_within, name='send_funds_within'),
    path('transaction_history/', transaction_history, name='transaction_history')

]

bankproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from home.views import home
from BankAccount import urls as bankurls

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  # User management
                  path("users/", include("user.urls", namespace="user")),
                  path("accounts/", include("allauth.urls")),
                  path("banking/",  include(bankurls)),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('home/', home, name="home"),
]

BankAccount/models.py
import uuid
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class BankAccount(models.Model):
    ACCOUNT_TYPES = (
        ('savings', 'Savings'),
        ('checking', 'Checking'),
        # Add more account types as needed
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    balance = models.FloatField(default=0)
    account_type = models.CharField(max_length=10, choices=ACCOUNT_TYPES)

    def __str__(self):
        return f"Bank Account {self.uid} ({self.user.username})"

BankAccount/forms.py
from django import forms
from .models import BankAccount


class BankAccountForm(forms.ModelForm):
    class Meta:
        model = BankAccount
        fields = ['account_type']

BankAccount/views.py
from datetime import datetime

from django.shortcuts import render, redirect
from django.utils import timezone

from transaction.models import Transaction
from .models import BankAccount
from .forms import BankAccountForm
from os import path
from pathlib import Path
from deposit.forms import DepositForm

ROOT_DIR = Path(__file__).resolve(strict=True).parent.parent
USER_TEMPLATES_DIR = path.join(ROOT_DIR, 'templates/bankaccount/')


def create_bank_account(request):
    if request.method == 'POST':
        form = BankAccountForm(request.POST)
        if form.is_valid():
            # Create bank account with the logged-in user as the owner
            bank_account = form.save(commit=False)
            bank_account.user = request.user
            bank_account.save()

            # Redirect to bank account details page
            return redirect('bank_account_details')
    else:
        form = BankAccountForm()

    context = {
        'form': form
    }
    return render(request, path.join(USER_TEMPLATES_DIR, 'create_bank_account.html'), context)


def bank_account_details(request):
    user = request.user
    bank_accounts = BankAccount.objects.filter(user=user)

    context = {
        'bank_accounts': bank_accounts
    }

    def execute_pending_transactions():
        pending_transactions = Transaction.objects.filter(status='pending')
        # get user bankaccounts
        user_bank_accounts = BankAccount.objects.filter(user=request.user)

        for transaction in pending_transactions:
            sender_account = transaction.sender
            receiver_account = transaction.receiver
            amount = transaction.amount
            date = transaction.date

            # Check if the sender's account is one of the user's bank accounts
            if sender_account in user_bank_accounts:
                # Check the balance and the date
                if sender_account.balance >= amount and date <= timezone.now():
                    # Perform the transfer
                    sender_account.balance -= amount
                    receiver_account.balance += amount
                    sender_account.save()
                    receiver_account.save()

                    # Update the transaction status
                    transaction.status = 'completed'
                    transaction.save()

                else:
                    # Update the transaction status to pending
                    transaction.status = 'pending'
                    transaction.save()
    execute_pending_transactions()
    return render(request, path.join(USER_TEMPLATES_DIR, 'bank_account_details.html'), context)

templates/bankaccount/bank_account_details.html
{% extends 'base.html' %}
{% block title %}Bank Account Details{% endblock %}

{% block content %}
  <h1>Bank Account Details</h1>
  {% if bank_accounts %}
    <ul>
      {% for account in bank_accounts %}
        <li>
          <strong>Account ID:</strong> {{ account.uid }}<br>
          <strong>Balance:</strong> ${{ account.balance }}<br>
          <strong>Account Type:</strong> {{ account.get_account_type_display }}
        </li>

        <br>
        <br>
        <br>
      {% endfor %}
    </ul>
          <a href="{% url 'create_bank_account'  %}" class="my-button">Create New Bank account</a>
          <a href="{% url 'transaction_history'  %}" class="my-button">History</a>
          <a href="{% url 'deposit_funds'  %}" class="my-button">Deposit</a>
         {% if bank_accounts|length > 1 %}
            <a href="{% url 'send_funds_within' %}" class="my-button">Send Between Accounts</a>
        {% endif %}
          <a href="{% url 'send_funds_out' %}" class="my-button">Send</a>
  {% else %}
    <p>No bank accounts found.</p>
    <a href="{% url 'create_bank_account'  %}" class="my-button">Create New Bank account</a>

  {% endif %}
{% endblock %}

templates/bankaccount/create_bank_account.html
{% extends 'base.html' %}

{% block title %}Create an Account{% endblock %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<form method="POST" class="create_account">
  {% csrf_token %}

  <div class="form-group">
    <label for="{{ form.account_type.id_for_label }}"><span class="small"></span></label>
    {{ form.account_type|as_crispy_field }}
  </div>
<button type="submit" class="btn btn-success">Create Account</button>
</form>
{% endblock %}