bankproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from home.views import home
from BankAccount import urls as bankurls

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  # User management
                  path("users/", include("user.urls", namespace="user")),
                  path("accounts/", include("allauth.urls")),
                  path("banking/",  include(bankurls)),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('home/', home, name="home"),
]

user/urls.py
from django.urls import path
from .views import LoginView, user_detail_view, user_update_view, user_delete_view, \
    user_create_view, user_redirect_view

app_name = "users"
urlpatterns = [
    path("<int:pk>/", view=user_update_view, name="user_update"),
    path("login/", view=LoginView.as_view(), name="user_login"),
    path("register/", user_create_view, name="register"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("<pk>/delete/", view=user_delete_view, name="delete"),
]

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Bank App</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>

    </style>
</head>
<body>
    <nav>
                <!--Profile-->
        {# URL provided by django-allauth/account/urls.py #}
        <ul>
            <li><a href="{% url 'home'%}" >Home</a></li>
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'users:detail' request.user.username  %}" >My Personal Information</a></li>
            <li><a href="{% url 'bank_account_details'%}" >My Banking Information</a></li>
            <li><a href="{% url 'account_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'account_login' %}">Sign In</a></li>
            <li><a href="{% url 'users:register' %}">Sign Up</a></li>
            {% endif %}

        </ul>
    </nav>

    <div class="content">
        {% block content %}
        {% endblock %}
    </div>

    <footer>
        &copy; 2023 Your Bank App. All rights reserved.
    </footer>
</body>
</html>