bankproject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from home.views import home
from BankAccount import urls as bankurls

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', home, name='home'),
                  # User management
                  path("users/", include("user.urls", namespace="user")),
                  path("accounts/", include("allauth.urls")),
                  path("banking/",  include(bankurls)),


              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('home/', home, name="home"),
]

user/urls.py
from django.urls import path
from .views import LoginView, user_detail_view, user_update_view, user_delete_view, \
    user_create_view, user_redirect_view

app_name = "users"
urlpatterns = [
    path("<int:pk>/", view=user_update_view, name="user_update"),
    path("login/", view=LoginView.as_view(), name="user_login"),
    path("register/", user_create_view, name="register"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("<pk>/delete/", view=user_delete_view, name="delete"),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, IntegerField, ImageField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    #: First and last name do not cover name patterns around the globe
    full_name = CharField(_("Name"), blank=True, max_length=255)
    email = EmailField(unique=True)
    password = CharField(max_length=255)
    profile_picture = ImageField(upload_to='images/profile_pictures', null=True, blank=True)
    address = CharField(max_length=255, null=True, blank=True)
    phone_number = IntegerField(null=True, blank=True)

    # Add unique related_name arguments
    groups = None  # Set to None to avoid clashes
    user_permissions = None  # Set to None to avoid clashes

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

user/forms.py
from django.contrib.auth import forms, get_user_model, password_validation
from django.core.exceptions import ValidationError
from django import forms as django_forms
from django.utils.translation import gettext_lazy as _
from user.models import User
from django.contrib.auth.forms import AuthenticationForm


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['last_name'].required = True
        self.fields['first_name'].required = True

    class Meta(forms.UserCreationForm.Meta):
        model = User
        fields = (
            'username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'profile_picture', 'address',
            'phone_number')

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])


class UserUpdateForm(django_forms.ModelForm):
    password1 = django_forms.CharField(
        label=_("Password"),
        strip=False,
        widget=django_forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = django_forms.CharField(
        label=_("Password confirmation"),
        widget=django_forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['last_name'].required = True
        self.fields['first_name'].required = True
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['profile_picture']

    class Meta:
        model = User
        fields = (
            'username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'profile_picture', 'address',
            'phone_number')


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['password'].widget.attrs['placeholder'] = 'Password'

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Note that both fields may be case-sensitive."),
        'inactive': _("This account is inactive."),
    }

    username = django_forms.CharField(
        label=_("Username"),
        max_length=150,
        widget=django_forms.TextInput(attrs={'autofocus': True}),
    )
    password = django_forms.CharField(
        label=_("Password"),
        strip=False,
        widget=django_forms.PasswordInput,
    )

user/views.py
from django.contrib.auth import authenticate, logout ,login
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView, DeleteView, CreateView, TemplateView
from os import path
from django.utils.translation import gettext_lazy as _

from django.views.generic.base import View
from .forms import UserCreationForm, UserUpdateForm
from django.shortcuts import redirect
from pathlib import Path

User = get_user_model()

ROOT_DIR = Path(__file__).resolve(strict=True).parent.parent
USER_TEMPLATES_DIR = path.join(ROOT_DIR, 'templates/user/')


class SuperUserMixin(PermissionRequiredMixin, LoginRequiredMixin):
    def has_permission(self):
        return self.request.user.is_superuser


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UseCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = path.join(USER_TEMPLATES_DIR, 'user_register.html')


user_create_view = UseCreateView.as_view()


class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User

    def get_success_url(self):
        return reverse("home")


user_delete_view = UserDeleteView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = path.join(USER_TEMPLATES_DIR, 'user_update.html')

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Updated with success")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


# Create your views here.


class LoginView(View):

    def post(self, request):
        username = request.POST.get('login')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            # correct username and password login the user
            print(auth.login(request, user))
            return redirect('home')

        else:
            messages.error(request,
                           "Error user/password is wrong")

            return redirect('account_login')

    def get(self, request):
        logout(request)
        response = JsonResponse({'message': 'Logout done'})
        return response

templates/user/user_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Account Deletion{% endblock %}

{% load static %}

{% block content %}
<div class="container">
  <div class="confirm-delete">
    <h1>Confirm Account Deletion</h1>
    <p>Are you sure you want to delete your account?</p>
    <form method="POST" class="delete-form">
      {% csrf_token %}

      <button type="submit" class="btn btn-danger">Delete Account</button>
      <a href="{% url 'users:detail' user.username %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
</div>
{% endblock %}

templates/user/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}User Details{% endblock %}

{% block content %}
<div class="container">
  <div class="left-section">
    <div class="profile-picture">
      {% if user.profile_picture %}
        <img class="profile-image" src="{{ user.profile_picture.url }}" alt="Profile Picture">
      {% else %}
        <p class="no-picture">No profile picture available</p>
      {% endif %}
    </div>
    <div class="user-information">
      <h1>User Details</h1>
      <p>Username: {{ user.username }}</p>
      <p>First Name: {{ user.first_name }}</p>
      <p>Last Name: {{ user.last_name }}</p>
      <p>Email: {{ user.email }}</p>
      <p>Address: {{ user.address }}</p>
      <p>Phone Number: {{ user.phone_number }}</p>
        <button>
          <a href="{% url 'users:user_update' user.pk %}" >Update Account</a>
        </button>
        <button>
          <a href="{% url 'users:delete' user.pk %}" >Delete Account</a>
        </button>
    </div>
    <div></div>
  </div>
</div>

{% endblock %}

templates/user/user_register.html
{% extends 'base.html' %}

{% block title %}Create an Account{% endblock %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<form method="POST" class="create_account" enctype="multipart/form-data" >
  {% csrf_token %}

  <div class="form-group">
    <label for="{{ form.username.id_for_label }}"><span class="small"></span></label>
    {{ form.username|as_crispy_field }}
  </div>

  <div class="form-group">
    <label for="{{ form.first_name.id_for_label }}"><span class="small"></span></label>
    {{ form.first_name|as_crispy_field }}
  </div>

  <div class="form-group">
    <label for="{{ form.last_name.id_for_label }}"><span class="small"></span></label>
    {{ form.last_name|as_crispy_field }}
  </div>
    <div class="form-group">
    <label for="{{ form.email.id_for_label }}"><span class="small"></span></label>
    {{ form.email|as_crispy_field }}
  </div>

  <div class="form-group">
    <label for="{{ form.password1.id_for_label }}"><span class="small">
    Your password can’t be too similar to your other personal information.
    Your password must contain at least 8 characters.
    Your password can’t be a commonly used password.
    Your password can’t be entirely numeric.</span></label>
    {{ form.password1|as_crispy_field }}
  </div>

  <div class="form-group">
    <label for="{{ form.password2.id_for_label }}"></label>
    {{ form.password2|as_crispy_field }}
  </div>

  <div class="form-group">
    <label for="{{ form.profile_picture.id_for_label }}"></label>
    {{ form.profile_picture|as_crispy_field }}
  </div>

  <div class="form-group">
    <label for="{{ form.address.id_for_label }}"></label>
    {{ form.address|as_crispy_field }}
  </div>

  <div class="form-group">
    <label for="{{ form.phone_number.id_for_label }}"></label>
    {{ form.phone_number|as_crispy_field }}
  </div>

  <button type="submit" class="btn btn-success">Register</button>
</form>
{% endblock %}

templates/user/user_update.html
{% extends 'base.html' %}

{% block title %}Update Account{% endblock %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <div class="update_account">
    <h1>Update Account</h1>
    <form method="POST" class="update-form" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-group">
        <label for="{{ form.username.id_for_label }}"><span class="small"></span></label>
        {{ form.username|as_crispy_field }}
      </div>

      <div class="form-group">
        <label for="{{ form.first_name.id_for_label }}"><span class="small"></span></label>
        {{ form.first_name|as_crispy_field }}
      </div>

      <div class="form-group">
        <label for="{{ form.last_name.id_for_label }}"><span class="small"></span></label>
        {{ form.last_name|as_crispy_field }}
      </div>

      <div class="form-group">
        <label for="{{ form.email.id_for_label }}"><span class="small"></span></label>
        {{ form.email|as_crispy_field }}
      </div>

      <div class="form-group">
        <label for="{{ form.password1.id_for_label }}"><span class="small"></span></label>
        {{ form.password1|as_crispy_field }}
      </div>

      <div class="form-group">
        <label for="{{ form.password2.id_for_label }}"><span class="small"></span></label>
        {{ form.password2|as_crispy_field }}
      </div>

      <div class="form-group">
        <label for="{{ form.profile_picture.id_for_label }}"></label>
        {{ form.profile_picture|as_crispy_field }}
      </div>

      <div class="form-group">
        <label for="{{ form.address.id_for_label }}"></label>
        {{ form.address|as_crispy_field }}
      </div>

      <div class="form-group">
        <label for="{{ form.phone_number.id_for_label }}"></label>
        {{ form.phone_number|as_crispy_field }}
      </div>

      <button type="submit" class="btn btn-success">Update Account</button>
    </form>
  </div>
</div>
{% endblock %}